
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run: pip install -r requirements_dev.txt

      - run:
          command: python -m unittest
