
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements_dev.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements_dev.txt" }}
          paths:
            - "venv"
      - run:
          name: Run unittests
          command:
            . venv/bin/activate
            python -m unittest
